Develop
SuitsU/IliasUpdateNotification pull request #1
Opened 2022-10-08 09:52 UTC by chrisIlias1993

2022-11-05 15:02 UTC, colin-kiegel commented on classes/class.ilUpdateNotificationJob.php
> +                return "$major.$minor";
return value sollte hier nur `$major` sein - der Sprachgebrauch in der Community ist "ILIAS 8" und nicht "ILIAS 8.0" um eine Major-Version zu bezeichnen.

2022-11-05 15:03 UTC, colin-kiegel commented on classes/class.ilUpdateNotificationJob.php
> +            $return = $mail->sendMail(
`$return` Variable hat keine Verwendung

2022-11-07 07:28 UTC, mjansenDatabay requested changes
Hi @chrisIlias1993 and @colin-kiegel ,

- Class `ilUpdateNotificationJob` does not follow the `Single Responsibility Principle`. It handles a bunch of different tasks. You should extract these to seperate classes/interfaces. Maybe it is worth create folders/namespaces for `Domain`, `Infrastructure`, `Application` etc.
  - Retrieving a `array<int, string>` map for presentation purposes in forms
  - Retrieving a list of `int` role ids for validation purposes
  - Executing SQL statements with `ilDBInterface`
  - Fetching external content with `cURL`
  - Checking whether a new ILIAS version is available
  - Sending notifications (emails)
  - Managing instances of `ilADNNotification`
- I suggest to apply the `PSR-12` coding standard to the PHP source files.
- We already have a `cURL` wrapper, `ilCurlConnection
- Please avoid `AND` and `OR`, use `||` and `&&` as logical operators

Best regards
@mjansenDatabay

2022-11-12 13:15 UTC, chrisIlias1993 commented on classes/class.ilUpdateNotificationJob.php
> +            $return = $mail->sendMail(
✅

2022-11-12 13:15 UTC, chrisIlias1993 commented on classes/class.ilUpdateNotificationJob.php
> +        $il_adn_notification->setTypeDuringEvent(self::TYPE_ERROR);
✅

2022-11-12 13:17 UTC, chrisIlias1993 commented on README.md
> +Developer: [chrisIlias1993](https://github.com/chrisIlias1993)
✅

2022-11-12 13:18 UTC, chrisIlias1993 commented
Mach du mal besser den Merge, sollte nun alles soweit passen.

2022-11-23 18:00 UTC, colin-kiegel commented on classes/class.ilUpdateNotificationJob.php
> +        $body = str_replace('[MAJOR_RELEASE_URL]', $major_release_url, $body);
@chrisIlias1993 `mayor` mit y heißt Bürgermeister und wird auch etwas anders ausgesprochen als `major` mit j für Haupt...

Ich habe den Fehler an verschiedenen Stellen korrigiert.

2022-11-23 18:16 UTC, colin-kiegel commented
Bitte Fehler #9 beheben

2023-01-21 09:25 UTC, merged